version: '3'

services:
  api-gateway:
    build:
      context: ./apps/api-gateway
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./apps/backend
    ports:
      - "3001:3001"
    depends_on:
      - api-gateway

  payment-service:
    build:
      context: ./apps/payment-service
    ports:
      - "3002:3002"
    depends_on:
      - api-gateway

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - backend
      - payment-service
