apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-deploy
  template:
    metadata:
      labels:
        app: payment-service-deploy
    spec:
      containers:
        - name: payment-service-deploy  # <--- This is the name of the container
          image: sergehall/lens-lounge-payment-service
          resources:
            limits:
              memory: "256Mi" # <--- This is the maximum amount of memory that the container can use
              cpu: "250m"  # <--- This is the maximum amount of CPU that the container can use
          ports:
            - containerPort: 82 # <--- This is the port that the container is listening on
              protocol: TCP # <--- This is the protocol that the container is listening on
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-deploy
spec:
  type: ClusterIP
  selector:
    app: payment-service-deploy
  ports:
    - protocol: TCP
      port: 82
      targetPort: 82
