apiVersion: v1
kind: Service
metadata:
  name: lens-lounge-m
spec:
  selector:
    app: lens-lounge-m  # <--- This is the label that the service will select
  ports:
    - protocol: TCP
      port: 5000  # <--- This is the port that the service will be listening on
      targetPort: 5001 # <--- This is the port that the container is listening on
  type: LoadBalancer
